name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-linux:
    name: Build Linux Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Create archive
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          mkdir -p release
          cp target/release/wallrust release/
          cd release
          tar -czvf wallrust-${VERSION}-linux-x86_64.tar.gz wallrust
          cd ..

      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/wallrust-*-linux-x86_64.tar.gz
          generate_release_notes: true

  build-macos-intel:
    name: Build macOS Intel Binary
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          target: x86_64-apple-darwin

      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-apple-darwin

      - name: Create archive
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          mkdir -p release
          cp target/x86_64-apple-darwin/release/wallrust release/
          cd release
          tar -czvf wallrust-${VERSION}-macos-x86_64.tar.gz wallrust
          cd ..

      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/wallrust-*-macos-x86_64.tar.gz

  build-macos-arm:
    name: Build macOS Apple Silicon Binary
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          target: aarch64-apple-darwin

      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target aarch64-apple-darwin

      - name: Create archive
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          mkdir -p release
          cp target/aarch64-apple-darwin/release/wallrust release/
          cd release
          tar -czvf wallrust-${VERSION}-macos-arm64.tar.gz wallrust
          cd ..

      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/wallrust-*-macos-arm64.tar.gz
